### ISSUE TITLE
App Transport Security broke this beautiful thing

### ISSUE THREAD

**Issue by stjohnmccloskey** [alexwasserman/GeekWeather2#7]
I hope that someone much wiser than I am will be able to save it. I've used it and loved it for what seemed like ages, but now it will not work because of some new security features of El Cap. It's sad.

**Comment by alexwasserman** [comment]
Pushed an update to switch to HTTPS instead of HTTP. Should resolve the issue in using Webkit2png - see https://github.com/paulhammond/webkit2png/issues/90
